require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipotratamentosController do

  # This should return the minimal set of attributes required to create a valid
  # Tipotratamento. As you add validations to Tipotratamento, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "tipo" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipotratamentosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipotratamentos as @tipotratamentos" do
      tipotratamento = Tipotratamento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipotratamentos).should eq([tipotratamento])
    end
  end

  describe "GET show" do
    it "assigns the requested tipotratamento as @tipotratamento" do
      tipotratamento = Tipotratamento.create! valid_attributes
      get :show, {:id => tipotratamento.to_param}, valid_session
      assigns(:tipotratamento).should eq(tipotratamento)
    end
  end

  describe "GET new" do
    it "assigns a new tipotratamento as @tipotratamento" do
      get :new, {}, valid_session
      assigns(:tipotratamento).should be_a_new(Tipotratamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipotratamento as @tipotratamento" do
      tipotratamento = Tipotratamento.create! valid_attributes
      get :edit, {:id => tipotratamento.to_param}, valid_session
      assigns(:tipotratamento).should eq(tipotratamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tipotratamento" do
        expect {
          post :create, {:tipotratamento => valid_attributes}, valid_session
        }.to change(Tipotratamento, :count).by(1)
      end

      it "assigns a newly created tipotratamento as @tipotratamento" do
        post :create, {:tipotratamento => valid_attributes}, valid_session
        assigns(:tipotratamento).should be_a(Tipotratamento)
        assigns(:tipotratamento).should be_persisted
      end

      it "redirects to the created tipotratamento" do
        post :create, {:tipotratamento => valid_attributes}, valid_session
        response.should redirect_to(Tipotratamento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipotratamento as @tipotratamento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotratamento.any_instance.stub(:save).and_return(false)
        post :create, {:tipotratamento => { "tipo" => "invalid value" }}, valid_session
        assigns(:tipotratamento).should be_a_new(Tipotratamento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotratamento.any_instance.stub(:save).and_return(false)
        post :create, {:tipotratamento => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipotratamento" do
        tipotratamento = Tipotratamento.create! valid_attributes
        # Assuming there are no other tipotratamentos in the database, this
        # specifies that the Tipotratamento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tipotratamento.any_instance.should_receive(:update_attributes).with({ "tipo" => "MyString" })
        put :update, {:id => tipotratamento.to_param, :tipotratamento => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested tipotratamento as @tipotratamento" do
        tipotratamento = Tipotratamento.create! valid_attributes
        put :update, {:id => tipotratamento.to_param, :tipotratamento => valid_attributes}, valid_session
        assigns(:tipotratamento).should eq(tipotratamento)
      end

      it "redirects to the tipotratamento" do
        tipotratamento = Tipotratamento.create! valid_attributes
        put :update, {:id => tipotratamento.to_param, :tipotratamento => valid_attributes}, valid_session
        response.should redirect_to(tipotratamento)
      end
    end

    describe "with invalid params" do
      it "assigns the tipotratamento as @tipotratamento" do
        tipotratamento = Tipotratamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotratamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipotratamento.to_param, :tipotratamento => { "tipo" => "invalid value" }}, valid_session
        assigns(:tipotratamento).should eq(tipotratamento)
      end

      it "re-renders the 'edit' template" do
        tipotratamento = Tipotratamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotratamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipotratamento.to_param, :tipotratamento => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipotratamento" do
      tipotratamento = Tipotratamento.create! valid_attributes
      expect {
        delete :destroy, {:id => tipotratamento.to_param}, valid_session
      }.to change(Tipotratamento, :count).by(-1)
    end

    it "redirects to the tipotratamentos list" do
      tipotratamento = Tipotratamento.create! valid_attributes
      delete :destroy, {:id => tipotratamento.to_param}, valid_session
      response.should redirect_to(tipotratamentos_url)
    end
  end

end
