require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipodoencasController do

  # This should return the minimal set of attributes required to create a valid
  # Tipodoenca. As you add validations to Tipodoenca, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "tipo" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipodoencasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipodoencas as @tipodoencas" do
      tipodoenca = Tipodoenca.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipodoencas).should eq([tipodoenca])
    end
  end

  describe "GET show" do
    it "assigns the requested tipodoenca as @tipodoenca" do
      tipodoenca = Tipodoenca.create! valid_attributes
      get :show, {:id => tipodoenca.to_param}, valid_session
      assigns(:tipodoenca).should eq(tipodoenca)
    end
  end

  describe "GET new" do
    it "assigns a new tipodoenca as @tipodoenca" do
      get :new, {}, valid_session
      assigns(:tipodoenca).should be_a_new(Tipodoenca)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipodoenca as @tipodoenca" do
      tipodoenca = Tipodoenca.create! valid_attributes
      get :edit, {:id => tipodoenca.to_param}, valid_session
      assigns(:tipodoenca).should eq(tipodoenca)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tipodoenca" do
        expect {
          post :create, {:tipodoenca => valid_attributes}, valid_session
        }.to change(Tipodoenca, :count).by(1)
      end

      it "assigns a newly created tipodoenca as @tipodoenca" do
        post :create, {:tipodoenca => valid_attributes}, valid_session
        assigns(:tipodoenca).should be_a(Tipodoenca)
        assigns(:tipodoenca).should be_persisted
      end

      it "redirects to the created tipodoenca" do
        post :create, {:tipodoenca => valid_attributes}, valid_session
        response.should redirect_to(Tipodoenca.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipodoenca as @tipodoenca" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipodoenca.any_instance.stub(:save).and_return(false)
        post :create, {:tipodoenca => { "tipo" => "invalid value" }}, valid_session
        assigns(:tipodoenca).should be_a_new(Tipodoenca)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipodoenca.any_instance.stub(:save).and_return(false)
        post :create, {:tipodoenca => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipodoenca" do
        tipodoenca = Tipodoenca.create! valid_attributes
        # Assuming there are no other tipodoencas in the database, this
        # specifies that the Tipodoenca created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tipodoenca.any_instance.should_receive(:update_attributes).with({ "tipo" => "MyString" })
        put :update, {:id => tipodoenca.to_param, :tipodoenca => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested tipodoenca as @tipodoenca" do
        tipodoenca = Tipodoenca.create! valid_attributes
        put :update, {:id => tipodoenca.to_param, :tipodoenca => valid_attributes}, valid_session
        assigns(:tipodoenca).should eq(tipodoenca)
      end

      it "redirects to the tipodoenca" do
        tipodoenca = Tipodoenca.create! valid_attributes
        put :update, {:id => tipodoenca.to_param, :tipodoenca => valid_attributes}, valid_session
        response.should redirect_to(tipodoenca)
      end
    end

    describe "with invalid params" do
      it "assigns the tipodoenca as @tipodoenca" do
        tipodoenca = Tipodoenca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipodoenca.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipodoenca.to_param, :tipodoenca => { "tipo" => "invalid value" }}, valid_session
        assigns(:tipodoenca).should eq(tipodoenca)
      end

      it "re-renders the 'edit' template" do
        tipodoenca = Tipodoenca.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipodoenca.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipodoenca.to_param, :tipodoenca => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipodoenca" do
      tipodoenca = Tipodoenca.create! valid_attributes
      expect {
        delete :destroy, {:id => tipodoenca.to_param}, valid_session
      }.to change(Tipodoenca, :count).by(-1)
    end

    it "redirects to the tipodoencas list" do
      tipodoenca = Tipodoenca.create! valid_attributes
      delete :destroy, {:id => tipodoenca.to_param}, valid_session
      response.should redirect_to(tipodoencas_url)
    end
  end

end
